// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIT-b2EyDFsGvZxpnprBVMfd7xw2tDNfY',
    appId: '1:586457874358:web:a205e5ee02f97198ea0b17',
    messagingSenderId: '586457874358',
    projectId: 'bootcamp-6dcc4',
    authDomain: 'bootcamp-6dcc4.firebaseapp.com',
    storageBucket: 'bootcamp-6dcc4.appspot.com',
    measurementId: 'G-5KFJ02EWZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqSDVBCg_EwslmIWdwPYAgK1LsHVpI28',
    appId: '1:586457874358:android:e8d3230da23bd711ea0b17',
    messagingSenderId: '586457874358',
    projectId: 'bootcamp-6dcc4',
    storageBucket: 'bootcamp-6dcc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdA6qJhML_T7P4H8C8sSYzKKkER-t0h_Q',
    appId: '1:586457874358:ios:ace5ca4f2f87ea52ea0b17',
    messagingSenderId: '586457874358',
    projectId: 'bootcamp-6dcc4',
    storageBucket: 'bootcamp-6dcc4.appspot.com',
    iosClientId: '586457874358-nos8q7jg5s4m0ogm3shd44bvfr0qato4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdA6qJhML_T7P4H8C8sSYzKKkER-t0h_Q',
    appId: '1:586457874358:ios:6214fd27597cb7d6ea0b17',
    messagingSenderId: '586457874358',
    projectId: 'bootcamp-6dcc4',
    storageBucket: 'bootcamp-6dcc4.appspot.com',
    iosClientId: '586457874358-79g5hggl648vch2q8tfg1s1p171v6tga.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcamp.RunnerTests',
  );
}
